libCubeEye: CubeEye.result_property Class Reference
CubeEye.result_property Class Reference
Public Member Functions
def __init__ (self, *args)
def __len__ (self)
def __repr__ (self)
def __getitem__ (self, index)
def __setitem__ (self, index, val)
Properties
thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
first = property(_CubeEye.result_property_first_get, _CubeEye.result_property_first_set, doc=)
second = property(_CubeEye.result_property_second_get, _CubeEye.result_property_second_set, doc=)
Static Private Attributes
__repr__ = _swig_repr
__swig_destroy__ = _CubeEye.delete_result_property
Detailed Description
Proxy of C++ std::pair< int,sptr_property > class.
Constructor & Destructor Documentation
__init__()
def CubeEye.result_property.__init__ (self, * args)
__init__(self) -> result_property
__init__(self, first, second) -> result_property
__init__(self, other) -> result_property
Member Function Documentation
__getitem__()
def CubeEye.result_property.__getitem__ (self, index)
References CubeEye.result_property.first, and CubeEye.result_property.second.
__len__()
def CubeEye.result_property.__len__ (self)
__repr__()
def CubeEye.result_property.__repr__ (self)
References CubeEye.result_property.__repr__, CubeEye.result_property.first, and CubeEye.result_property.second.
__setitem__()
def CubeEye.result_property.__setitem__ (self, index, val)
References CubeEye.result_property.first, and CubeEye.result_property.second.
Member Data Documentation
__repr__
CubeEye.result_property.__repr__ = _swig_repr static private
Referenced by CubeEye.result_property.__repr__().
__swig_destroy__
CubeEye.result_property.__swig_destroy__ = _CubeEye.delete_result_property static private
Property Documentation
first
CubeEye.result_property.first = property(_CubeEye.result_property_first_get, _CubeEye.result_property_first_set, doc=) static
Referenced by CubeEye.result_property.__getitem__(), CubeEye.result_properties.__getitem__(), CubeEye.fov.__getitem__(), CubeEye.result_property.__repr__(), CubeEye.result_properties.__repr__(), CubeEye.fov.__repr__(), CubeEye.result_property.__setitem__(), CubeEye.result_properties.__setitem__(), and CubeEye.fov.__setitem__().
second
CubeEye.result_property.second = property(_CubeEye.result_property_second_get, _CubeEye.result_property_second_set, doc=) static
Referenced by CubeEye.result_property.__getitem__(), CubeEye.result_properties.__getitem__(), CubeEye.fov.__getitem__(), CubeEye.result_property.__repr__(), CubeEye.result_properties.__repr__(), CubeEye.fov.__repr__(), CubeEye.result_property.__setitem__(), CubeEye.result_properties.__setitem__(), and CubeEye.fov.__setitem__().
thisown
CubeEye.result_property.thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag") static
The documentation for this class was generated from the following file:
header/CubeEye.py