libCubeEye: example Namespace Reference
example Namespace Reference
Classes
class _CubeEyeContext
class _CubeEyePythonSink
Functions
def get_camera_state (state)
def get_camera_error (error)
def get_camera_result (result)
def search_command (context, command_list)
def select_command (context, command_list)
def run_command (context, command_list)
def stop_command (context, command_list)
def set_command (context, command_list)
def get_command (context, command_list)
def help_command ()
def main ()
Function Documentation
get_camera_error()
def example.get_camera_error (error)
Referenced by example._CubeEyePythonSink.onCubeEyeCameraError().
get_camera_result()
def example.get_camera_result (result)
Referenced by get_command(), run_command(), set_command(), and stop_command().
get_camera_state()
def example.get_camera_state (state)
Referenced by example._CubeEyePythonSink.onCubeEyeCameraState().
get_command()
def example.get_command (context, command_list)
References get_camera_result().
help_command()
def example.help_command ()
Referenced by main().
main()
def example.main ()
References help_command().
run_command()
def example.run_command (context, command_list)
References get_camera_result().
search_command()
def example.search_command (context, command_list)
select_command()
def example.select_command (context, command_list)
set_command()
def example.set_command (context, command_list)
References get_camera_result().
stop_command()
def example.stop_command (context, command_list)
References get_camera_result().